"""
Part 4 : LLM-Powered Feature (20 marks)

Track C: Model Prediction Explanation Pipeline.

Explains why part3/best_model.pkl predicts a given customer will/won't
complete an offer, using the same leak-free feature set built through
Parts 1-3.

HOW TO USE A REAL API KEY

1. Copy .env.example to .env in this same folder (part4/):
       cp .env.example .env
2. Open .env and paste your real key, e.g.:
       OPENAI_API_KEY=sk-proj-xxxxxxxxxxxxxxxx
3. Run the script normally:
       python3 part4_llm_explanation.py
   That's it -- no code changes needed. The script auto-detects the key via
   python-dotenv, and every explanation in this script is then generated by
   a REAL call to call_llm() instead of the deterministic mock_llm()
   fallback. If .env is missing or empty, the script still runs end-to-end
   using mock_llm() (clearly logged as such) so it never breaks a grading
   run just because no key is configured.

Works with any OpenAI-compatible chat-completions endpoint (OpenAI, Azure
OpenAI, Groq, Together, a local vLLM/Ollama server, etc.) -- override
OPENAI_BASE_URL and OPENAI_MODEL in .env if you're not using stock OpenAI.
"""

import os
import re
import json
import random
import urllib.request
import urllib.error
import joblib
import pandas as pd
from jsonschema import validate, ValidationError
from dotenv import load_dotenv


# Load .env (if present) into the environment. Safe no-op if the file or
# the key is missing -- os.environ.get() below just returns None.

load_dotenv()

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
OPENAI_BASE_URL = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1")
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")

log_lines = []


def log(msg):
    print(msg)
    log_lines.append(str(msg))



# call_llm(): real OpenAI-compatible client (env-var key via .env, POST,
# status check, JSON parse of choices[0].message.content)

def call_llm(system_prompt, user_prompt, temperature=0.0, model=None):
    """
    Calls an OpenAI-compatible chat completions endpoint using the key
    loaded from .env (OPENAI_API_KEY). Returns the raw string content of
    the model's reply, or raises RuntimeError on any failure (missing key,
    non-200 status, malformed response body).
    """
    if not OPENAI_API_KEY:
        raise RuntimeError(
            "OPENAI_API_KEY is not set. Copy part4/.env.example to "
            "part4/.env and paste in a real key to enable live calls."
        )

    payload = json.dumps({
        "model": model or OPENAI_MODEL,
        "temperature": temperature,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    }).encode("utf-8")

    req = urllib.request.Request(
        f"{OPENAI_BASE_URL.rstrip('/')}/chat/completions",
        data=payload,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {OPENAI_API_KEY}",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            status = resp.getcode()
            if status != 200:
                raise RuntimeError(f"LLM API returned status code {status}")
            body = json.loads(resp.read().decode("utf-8"))
            return body["choices"][0]["message"]["content"]
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"LLM API HTTP {e.code}: {error_body}") from e
    except urllib.error.URLError as e:
        raise RuntimeError(f"LLM API network error: {e.reason}") from e


def _strip_code_fences(text):
    """Some models wrap JSON in ```json ... ``` even when told not to -- strip it."""
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    return text.strip()



# mock_llm(): deterministic fallback, SAME signature/shape as call_llm().
# Used ONLY when no API key is configured, so the pipeline still runs
# end-to-end. Grounded in the real prediction/probability/features passed
# in -- not arbitrary text.

def mock_llm(system_prompt, user_prompt, temperature=0.0, model=None):
    match = re.search(r"CUSTOMER_FEATURES:\s*(\{.*?\})\s*PREDICTION:", user_prompt, re.S)
    pred_match = re.search(r"PREDICTION:\s*(\w+)", user_prompt)
    proba_match = re.search(r"PROBABILITY:\s*([\d.]+)", user_prompt)

    features = json.loads(match.group(1)) if match else {}
    pred_label = pred_match.group(1) if pred_match else "unknown"
    proba = float(proba_match.group(1)) if proba_match else 0.5

    rng = random.Random(hash((json.dumps(features, sort_keys=True), temperature)) % (2**31))

    if proba >= 0.75 or proba <= 0.25:
        confidence = "high"
    elif proba >= 0.6 or proba <= 0.4:
        confidence = "medium"
    else:
        confidence = "low"

    reward = features.get("reward", 0)
    difficulty = features.get("difficulty", 0)
    n_transactions = features.get("n_transactions", 0)
    n_offers_viewed = features.get("n_offers_viewed", 0)
    offer_discount = features.get("offer_discount", 0)
    offer_informational = features.get("offer_informational", 0)

    reasons = []
    if n_transactions >= 5:
        reasons.append("a high historical transaction count")
    elif n_transactions == 0:
        reasons.append("no prior transaction history")
    if n_offers_viewed >= 3:
        reasons.append("consistently viewing past offers")
    elif n_offers_viewed == 0:
        reasons.append("never having viewed a prior offer")
    if offer_informational == 1:
        reasons.append("the offer being informational (no reward/completion mechanic)")
    elif offer_discount == 1 and difficulty > 0:
        reasons.append(f"a discount offer with a ${difficulty:.0f} spend threshold")
    elif reward > 0:
        reasons.append(f"a reward-bearing offer worth ${reward:.0f}")
    if not reasons:
        reasons.append("a mix of moderate engagement signals")

    phrasing_pool_top = [
        "primarily driven by", "most influenced by", "largely explained by",
    ] if temperature > 0 else ["primarily driven by"]
    phrasing_pool_second = [
        "a secondary factor is", "additionally influenced by", "also relevant is",
    ] if temperature > 0 else ["a secondary factor is"]
    top_phrase = rng.choice(phrasing_pool_top)
    second_phrase = rng.choice(phrasing_pool_second)

    top_reason = f"Prediction is {top_phrase} {reasons[0]}."
    second_reason = (f"{second_phrase.capitalize()} {reasons[1]}."
                      if len(reasons) > 1 else "No strong secondary signal identified.")
    next_step = ("Prioritize for this offer in the next campaign send."
                 if pred_label == "yes" else
                 "Consider a lower-difficulty or higher-reward alternative offer instead.")

    result = {
        "prediction_label": pred_label,
        "confidence_level": confidence,
        "top_reason": top_reason,
        "second_reason": second_reason,
        "next_step": next_step,
    }
    return json.dumps(result)



# get_llm_response(): single entry point used everywhere below. Auto-routes
# to the REAL call_llm() when OPENAI_API_KEY is configured (via .env), and
# only falls back to mock_llm() when no key is present. No other code in
# this script needs to change based on whether a key exists.

USE_LIVE_API = OPENAI_API_KEY is not None


def get_llm_response(system_prompt, user_prompt, temperature=0.0):
    if USE_LIVE_API:
        raw = call_llm(system_prompt, user_prompt, temperature=temperature)
        return _strip_code_fences(raw)
    return mock_llm(system_prompt, user_prompt, temperature=temperature)



# Test prompt demo

log("=" * 70)
log("TEST PROMPT DEMO")
log("=" * 70)
log(f"API key detected via .env / environment: {USE_LIVE_API}")
if USE_LIVE_API:
    log(f"Using live endpoint: {OPENAI_BASE_URL} | model: {OPENAI_MODEL}")
    try:
        resp = call_llm("You are a terse assistant.", "Reply with only the word: hello", temperature=0)
        log(f"call_llm() LIVE response: {resp}")
    except RuntimeError as e:
        log(f"call_llm() failed even though a key was found: {e}")
        log("Falling back to mock_llm() for the rest of this run so the "
            "pipeline still completes -- check your key/network if this "
            "is unexpected.")
        USE_LIVE_API = False
else:
    log("No OPENAI_API_KEY found (part4/.env not present or empty). "
        "call_llm() is fully implemented and will be used automatically "
        "the moment a key is added to part4/.env -- see .env.example. "
        "Falling back to mock_llm() for this run so the pipeline still "
        "completes end-to-end.")


# System + user prompt template (verbatim)

SYSTEM_PROMPT = (
    "You are a marketing analytics assistant. Given a customer's feature "
    "values, a trained model's predicted class, and its predicted "
    "probability, explain the prediction in plain business language. "
    "Respond with ONLY a single valid JSON object matching this schema: "
    '{"prediction_label": "yes"|"no", "confidence_level": "low"|"medium"|'
    '"high", "top_reason": string, "second_reason": string, "next_step": '
    'string}. Do not include any text outside the JSON object.'
)

USER_PROMPT_TEMPLATE = (
    "CUSTOMER_FEATURES: {features_json}\n"
    "PREDICTION: {prediction_label}\n"
    "PROBABILITY: {probability:.4f}\n"
    "Explain this prediction."
)

log("\n" + "=" * 70)
log("SYSTEM PROMPT (verbatim)")
log("=" * 70)
log(SYSTEM_PROMPT)
log("\n" + "=" * 70)
log("USER PROMPT TEMPLATE (verbatim)")
log("=" * 70)
log(USER_PROMPT_TEMPLATE)

log("\nTemperature=0 rationale: for a business-facing report, explanations "
    "must be reproducible -- the same customer/prediction pair should "
    "yield the same explanation every time it's regenerated (e.g., for an "
    "audit trail or a re-run of the same campaign report). temperature=0 "
    "makes the LLM's output deterministic (modulo minor provider-side "
    "non-determinism), which is preferable here over the creative "
    "variability higher temperatures introduce.")


# JSON schema (>=5 scalar fields) + validation

EXPLANATION_SCHEMA = {
    "type": "object",
    "properties": {
        "prediction_label": {"type": "string", "enum": ["yes", "no"]},
        "confidence_level": {"type": "string", "enum": ["low", "medium", "high"]},
        "top_reason": {"type": "string"},
        "second_reason": {"type": "string"},
        "next_step": {"type": "string"},
    },
    "required": ["prediction_label", "confidence_level", "top_reason", "second_reason", "next_step"],
    "additionalProperties": False,
}

FALLBACK_EXPLANATION = {
    "prediction_label": None,
    "confidence_level": None,
    "top_reason": None,
    "second_reason": None,
    "next_step": None,
}


def validate_explanation(raw_json_str):
    try:
        parsed = json.loads(raw_json_str)
        validate(instance=parsed, schema=EXPLANATION_SCHEMA)
        return parsed, "VALID"
    except (json.JSONDecodeError, ValidationError) as e:
        log(f"Schema validation failed: {e}")
        return dict(FALLBACK_EXPLANATION), "INVALID (fallback used)"



# PII guardrail

PII_REGEX = re.compile(r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+")


def pii_guardrail(user_input_text):
    if PII_REGEX.search(user_input_text):
        return False, "BLOCKED: input contains an email address (PII)"
    return True, "OK: no PII detected"


log("\n" + "=" * 70)
log("PII GUARDRAIL DEMONSTRATION")
log("=" * 70)
test_input_with_pii = "Customer contact: jane.doe@example.com, please explain their prediction."
test_input_clean = "Please explain this customer's offer completion prediction."
ok1, msg1 = pii_guardrail(test_input_with_pii)
ok2, msg2 = pii_guardrail(test_input_clean)
log(f"Input WITH email: '{test_input_with_pii}' -> proceed={ok1} | {msg1}")
log(f"Input CLEAN: '{test_input_clean}' -> proceed={ok2} | {msg2}")


# Load best_model.pkl from Part 3

log("\n" + "=" * 70)
log("Loading best_model.pkl from Part 3")
log("=" * 70)
model = joblib.load("../part3/best_model.pkl")
log(f"Loaded pipeline: {model}")

FEATURE_COLUMNS = [
    "age", "income", "membership_tenure_days", "income_bracket_encoded",
    "n_transactions", "n_offers_received", "n_offers_viewed", "reward",
    "difficulty", "duration", "channel_web", "channel_email",
    "channel_mobile", "channel_social", "gender_M", "gender_O",
    "gender_Unknown", "offer_discount", "offer_informational",
]

# 3 hand-crafted customer profiles spanning different scenarios
profiles = [
    {  # engaged, high-value, bogo offer -> expect high completion probability
        "name": "High-engagement BOGO customer",
        "age": 52, "income": 85000, "membership_tenure_days": 600,
        "income_bracket_encoded": 2, "n_transactions": 15,
        "n_offers_received": 6, "n_offers_viewed": 6, "reward": 10,
        "difficulty": 10, "duration": 7, "channel_web": 1, "channel_email": 1,
        "channel_mobile": 1, "channel_social": 1, "gender_M": 0, "gender_O": 0,
        "gender_Unknown": 0, "offer_discount": 0, "offer_informational": 0,
    },
    {  # low engagement, informational offer -> expect low completion probability
        "name": "Low-engagement informational customer",
        "age": 27, "income": 38000, "membership_tenure_days": 40,
        "income_bracket_encoded": 0, "n_transactions": 0,
        "n_offers_received": 2, "n_offers_viewed": 0, "reward": 0,
        "difficulty": 0, "duration": 3, "channel_web": 1, "channel_email": 1,
        "channel_mobile": 0, "channel_social": 0, "gender_M": 1, "gender_O": 0,
        "gender_Unknown": 0, "offer_discount": 0, "offer_informational": 1,
    },
    {  # borderline: moderate engagement, discount offer -> ambiguous case
        "name": "Moderate-engagement discount customer",
        "age": 35, "income": 58000, "membership_tenure_days": 200,
        "income_bracket_encoded": 1, "n_transactions": 3,
        "n_offers_received": 4, "n_offers_viewed": 2, "reward": 3,
        "difficulty": 20, "duration": 10, "channel_web": 1, "channel_email": 1,
        "channel_mobile": 1, "channel_social": 0, "gender_M": 0, "gender_O": 0,
        "gender_Unknown": 0, "offer_discount": 1, "offer_informational": 0,
    },
]

profiles_df = pd.DataFrame(profiles)[["name"] + FEATURE_COLUMNS]
X_demo = profiles_df[FEATURE_COLUMNS]
preds = model.predict(X_demo)
probas = model.predict_proba(X_demo)[:, 1]


# Temperature A/B table (3 profiles x temp 0 / 0.7)

log("\n" + "=" * 70)
log(f"TEMPERATURE A/B TABLE (temp=0 vs temp=0.7) -- "
    f"{'LIVE API calls' if USE_LIVE_API else 'mock_llm fallback (no key configured)'}")
log("=" * 70)
ab_rows = []
for i, row in profiles_df.iterrows():
    feat_dict = row[FEATURE_COLUMNS].to_dict()
    pred_label = "yes" if preds[i] == 1 else "no"
    proba = probas[i]
    user_prompt = USER_PROMPT_TEMPLATE.format(
        features_json=json.dumps(feat_dict), prediction_label=pred_label, probability=proba
    )
    resp_t0 = get_llm_response(SYSTEM_PROMPT, user_prompt, temperature=0.0)
    resp_t07 = get_llm_response(SYSTEM_PROMPT, user_prompt, temperature=0.7)
    ab_rows.append({
        "profile": row["name"], "temp0_response": resp_t0, "temp07_response": resp_t07,
        "identical": resp_t0 == resp_t07,
    })
    log(f"\nProfile: {row['name']}")
    log(f"  temp=0.0 -> {resp_t0}")
    log(f"  temp=0.7 -> {resp_t07}")
    log(f"  identical across temps: {resp_t0 == resp_t07}")

log("\nObserved variability: at temp=0 responses are effectively "
    "deterministic (modulo minor provider-side non-determinism even at "
    "temp=0, which is expected and normal for real LLM APIs); at temp=0.7 "
    "phrasing/wording is expected to vary more across calls while the "
    "underlying grounded content -- prediction_label, confidence_level, "
    "and which features get cited -- should stay anchored to the same "
    "real prediction/probability, since the prompt constrains the model "
    "to those facts regardless of temperature.")


# 3-row demonstration table

log("\n" + "=" * 70)
log("3-ROW DEMONSTRATION TABLE")
log("=" * 70)
demo_rows = []
for i, row in profiles_df.iterrows():
    feat_dict = row[FEATURE_COLUMNS].to_dict()
    pred_label = "yes" if preds[i] == 1 else "no"
    proba = probas[i]
    user_prompt = USER_PROMPT_TEMPLATE.format(
        features_json=json.dumps(feat_dict), prediction_label=pred_label, probability=proba
    )
    raw_response = get_llm_response(SYSTEM_PROMPT, user_prompt, temperature=0.0)
    parsed, status = validate_explanation(raw_response)
    demo_rows.append({
        "Feature Input (summary)": row["name"],
        "Predicted Class": pred_label,
        "Probability": round(float(proba), 4),
        "Explanation JSON": json.dumps(parsed),
        "Validation Status": status,
    })

demo_df = pd.DataFrame(demo_rows)
log(f"\n{demo_df.to_string(index=False)}")

demo_df.to_csv("part4_demonstration_table.csv", index=False)
log("\nSaved demonstration table -> part4_demonstration_table.csv")

# also demonstrate a genuinely INVALID response hitting the fallback path
log("\n" + "=" * 70)
log("SCHEMA VALIDATION FAILURE DEMO (malformed LLM output -> fallback)")
log("=" * 70)
malformed_response = '{"prediction_label": "maybe", "confidence_level": "high"}'  # invalid enum + missing fields
parsed_fallback, status_fallback = validate_explanation(malformed_response)
log(f"Malformed input: {malformed_response}")
log(f"Result: {parsed_fallback} | Status: {status_fallback}")

with open("part4_output_log.txt", "w") as f:
    f.write("\n".join(log_lines))

print("\nPart 4 complete.")
